import re
from sqlalchemy import MetaData, select, func, and_, desc, asc, text
from nl2dsl.dsl.models import DSL
from nl2dsl.exceptions import ValidationError


# Valid SQL aggregation function names (whitelist)
_VALID_AGG_FUNCS = {"sum", "avg", "count", "min", "max"}


class SQLBuilder:
    def __init__(self, engine, table_mapping: dict[str, str]):
        self._engine = engine
        self._metadata = MetaData()
        self._metadata.reflect(bind=engine)
        self._table_mapping = table_mapping

    def _parse_expr(self, expr: str) -> tuple[str, str]:
        """Parse 'SUM(order_amount)' -> ('sum', 'order_amount').

        Raises ValidationError if expression is malformed or unsafe.
        """
        match = re.match(r"^([A-Za-z_]+)\(([A-Za-z_][A-Za-z0-9_]*)\)$", expr)
        if not match:
            raise ValidationError(f"Invalid metric expression: {expr}")
        func_name = match.group(1).lower()
        column_name = match.group(2)
        if func_name not in _VALID_AGG_FUNCS:
            raise ValidationError(f"Unsupported aggregation function: {func_name}")
        return func_name, column_name

    def build(self, dsl: DSL) -> str:
        table_name = self._table_mapping.get(dsl.data_source, dsl.data_source)
        table = self._metadata.tables[table_name]

        # Build select columns
        columns = []
        if dsl.dimensions:
            for dim in dsl.dimensions:
                if dim not in table.c:
                    raise ValidationError(f"Dimension column '{dim}' not found in table '{table_name}'")
                columns.append(table.c[dim])

        if dsl.metrics:
            for metric in dsl.metrics:
                if "(" in metric.field:
                    # Resolved expression like SUM(order_amount)
                    func_name, col_name = self._parse_expr(metric.field)
                    agg_fn = getattr(func, func_name)
                    if col_name not in table.c:
                        raise ValidationError(f"Metric column '{col_name}' not found in table '{table_name}'")
                    col = agg_fn(table.c[col_name]).label(metric.alias or metric.field)
                else:
                    agg_fn = getattr(func, metric.func)
                    if metric.field not in table.c:
                        raise ValidationError(f"Metric column '{metric.field}' not found in table '{table_name}'")
                    col = agg_fn(table.c[metric.field]).label(metric.alias or metric.field)
                columns.append(col)

        stmt = select(*columns)

        # Build where
        conditions = []
        if dsl.filters:
            for f in dsl.filters:
                if f.field not in table.c:
                    raise ValidationError(f"Filter column '{f.field}' not found in table '{table_name}'")
                col = table.c[f.field]
                if f.operator == "=":
                    conditions.append(col == f.value)
                elif f.operator == "!=":
                    conditions.append(col != f.value)
                elif f.operator == ">":
                    conditions.append(col > f.value)
                elif f.operator == "<":
                    conditions.append(col < f.value)
                elif f.operator == ">=":
                    conditions.append(col >= f.value)
                elif f.operator == "<=":
                    conditions.append(col <= f.value)
                elif f.operator == "in":
                    conditions.append(col.in_(f.value))
                elif f.operator == "like":
                    conditions.append(col.like(f"%{f.value}%"))

        if conditions:
            stmt = stmt.where(and_(*conditions))

        # Group by
        if dsl.dimensions and dsl.metrics:
            stmt = stmt.group_by(*[table.c[d] for d in dsl.dimensions])

        # Collect metric aliases for ORDER BY resolution
        metric_aliases = {m.alias for m in (dsl.metrics or []) if m.alias}

        # Order by
        if dsl.order_by:
            for ob in dsl.order_by:
                col = table.c.get(ob.field)
                if col is not None:
                    # Table column
                    if ob.direction == "desc":
                        stmt = stmt.order_by(col.desc())
                    else:
                        stmt = stmt.order_by(col.asc())
                elif ob.field in metric_aliases:
                    # Metric alias (safe: generated by the system, not user input)
                    if ob.direction == "desc":
                        stmt = stmt.order_by(desc(text(ob.field)))
                    else:
                        stmt = stmt.order_by(asc(text(ob.field)))
                else:
                    raise ValidationError(f"ORDER BY field '{ob.field}' not found in table '{table_name}' or metric aliases")

        # Limit
        if dsl.limit:
            stmt = stmt.limit(dsl.limit)
        if dsl.offset:
            stmt = stmt.offset(dsl.offset)

        return str(stmt.compile(self._engine, compile_kwargs={"literal_binds": True}))
